apiVersion: v1
kind: Secret
metadata:
  name: postgres-task-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 for "postgres"
  POSTGRES_PASSWORD: MTIzNA==  # base64 for "1234"
  POSTGRES_DB: dGFza19kYg== # base64 for "task_db"
