apiVersion: v1
kind: Secret
metadata:
  name: mongo-comment-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==     # "root"
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ== # "example"
  URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby1jb21tZW50LTAubW9uZ28tY29tbWVudDoyNzAxNy9jb21tZW50X2RiP2F1dGhTb3VyY2U9YWRtaW4=
  # "mongodb://root:example@mongo-comment-0.mongo-comment:27017/comment_db?authSource=admin"
