apiVersion: v1
kind: Secret
metadata:
  name: mongo-comment-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==     # "root"
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ== # "example"
  URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby0wLm1vbmdvOjI3MDE3L2NvbW1lbnRfZGI/YXV0aFNvdXJjZT1hZG1pbg==
  # "mongodb://root:example@mongo-0.mongo:27017/comment_db?authSource=admin"
